CREATE TABLE [dbo].[Review] (
    [ReviewId]         TINYINT          IDENTITY (1, 1) NOT NULL,
    [PropertyID]       TINYINT          NOT NULL,
    [Company]          VARCHAR (256)    NULL,
    [Description]      VARCHAR (2000)   NOT NULL,
    [PrivateNote]      VARCHAR (2000)   NULL,
    [Name]             VARCHAR (256)    NOT NULL,
    [EmailAddress]     VARCHAR (100)    NULL,
    [Position]         VARCHAR (100)    NULL,
    [Rating]           TINYINT          NOT NULL,
    [Cleanliness]      TINYINT          NULL,
    [Accuracy]         TINYINT          NULL,
    [Communication]    TINYINT          NULL,
    [Location]         TINYINT          NULL,
    [Checkin]          TINYINT          NULL,
    [Facilities]       TINYINT          NULL,
    [Comfort]          TINYINT          NULL,
    [Value]            TINYINT          NULL,
    [ReviewTypeId]     TINYINT          NULL,
    [LinkToView]       VARCHAR (256)    NULL,
    [ShowOnHomepage]   BIT              NULL,
    [DateTimeAdded]    DATETIME2 (0)    NULL,
    [RegistrationCode] UNIQUEIDENTIFIER CONSTRAINT [DF_Review_RegistrationCode] DEFAULT (newsequentialid()) NOT NULL,
    [DateTimeApproved] DATETIME2 (0)    NULL,
    [Approved]         BIT              CONSTRAINT [DF_Review_Approved] DEFAULT ((0)) NOT NULL,
    [Created]          DATETIME2 (0)    NOT NULL,
    CONSTRAINT [PK_Review] PRIMARY KEY CLUSTERED ([ReviewId] ASC),
    CONSTRAINT [FK_Review_ReviewType] FOREIGN KEY ([ReviewTypeId]) REFERENCES [dbo].[ReviewType] ([ReviewTypeId]),
    CONSTRAINT [FK_Review_Property] FOREIGN KEY ([PropertyID]) REFERENCES [dbo].[Property] ([ID])
);

